### ISSUE TITLE
Borderless Window Glitches

### ISSUE THREAD

**Issue by VanillaCold** [Splitwirez/Spore-Mod-Manager#30]
1. When Spore encounters an error on startup. the error appears as a fullscreen borderless window.
![image](https://cdn.discordapp.com/attachments/438730672736305153/829296991401934908/unknown.png)

2. If the Spore Mod Manager is set to launch Spore as a borderless window but then the option to override Spore's window mode is disabled, Spore still starts as a fullscreen, borderless window.

3. When launching Spore as a borderless window through the Spore Mod Launcher instead of through the Spore Mod Manager, there's a high chance that this error will appear:
![image](https://user-images.githubusercontent.com/35960636/113909191-50874980-97cf-11eb-9dfc-90aec63a9a69.png)
Closing the error forces Spore to close, unless you close the Spore Mod Launcher instead.

**Comment by VanillaCold** [comment]
Update: after updating to 1.7.3.0, launching Spore as a borderless window acts the same as launching it as a regular window. It doesn't put Spore into borderless windowed mode anymore.

**Comment by Splitwirez** [comment]
I've opened a new issue for the sole remaining component of this one. Closing this composite issue since the rest of it has been addressed.

 @VanillaCold I really appreciate your ongoing initiative in filing these bug reports. Thank you. But in case I haven't already mentioned this to you before...please try to keep it to one issue per post. Makes things easier to manage. Thanks.
